name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: 22f3001011@ds.study.iitm.ac.in
        run: echo "Hello, world!"
